apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-redis
  template:
    metadata:
      labels:
        app: php-redis
    spec:
      containers:
      - name: foo
        image: gcr.io/google_samples/gb-frontend:v3
